#!/usr/bin/env python3
# Download all my Things

import argparse
import configparser
import requests


CONFIGFILE = './config'


# Read args from CLI
parser = argparse.ArgumentParser()
parser.add_argument("-o", "--outdir", nargs='?', default="/tmp", help="DIRECTORY to download things into")
args = parser.parse_args()

print("Downloading Things to: {}".format(args.outdir))


# Load from config
config = configparser.ConfigParser()
config.read(CONFIGFILE)
apiUrl = config['main']['API_URL']
accessToken = config['main']['ACCESS_TOKEN']


# Get list of my Things


# Download each Thing

